name: 'sw_wip'
version: 0.0.1
description: An absolute bare-bones web app.

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  angular2: ^2.2.0
  dart_style: ^0.2.16
  js: ^0.6.1
  service_worker: ^0.0.1

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
